admin/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.academia.urls', namespace='academia')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.site.site_header = 'Academy Factory'

apps/academia/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cliente/$', views.base, name='home'),

]

apps/academia/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Pessoa(models.Model):
    cpf = models.CharField(primary_key=True, max_length=14, verbose_name=_('Pessoa - CPF'))
    #data_nasc = models.DateField(verbose_name=_('Data de Nascimento'))
    #endereco = models.CharField(max_length=200, verbose_name=_('Endereço'))
    #telefone = models.CharField(max_length=16, verbose_name=_('Telefone'))
    #celular = models.CharField(max_length=16, verbose_name=_('Celular'))
    foto = models.ImageField(upload_to='funcionario')
    user = models.ForeignKey(User)

    def __str__(self):
        return str(self.user)

class FotosEstrutura(models.Model):
    foto = models.ImageField(upload_to='Foto')
    titulo = models.CharField(max_length=50, verbose_name='Titulo')
    descricao = models.CharField(max_length=50, verbose_name='Descricao')

    def __str__(self):
       return str(self.titulo)

class Precos(models.Model):
    tipo = models.CharField(max_length=50, verbose_name='Tipo')
    instrutor = models.CharField(max_length=50, verbose_name='Instrutos')
    faltas = models.CharField(max_length=50, verbose_name='Faltas')
    idas = models.CharField(max_length=50, verbose_name='Idas')
    horario = models.CharField(max_length=50, verbose_name='Horario')
    valor = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Valor')

    def __str__(self):
       return str(self.tipo)

class Servicos(models.Model):
    foto = models.ImageField(upload_to='Foto')
    titulo = models.CharField(max_length=50, verbose_name='Titulo')
    descricao = models.CharField(max_length=50, verbose_name='Descricao')

    def __str__(self):
       return str(self.titulo)

apps/cliente/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
# Create your models here.
from apps.academia.models import Pessoa


class Cliente(models.Model):
    mensalidade = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Mensalidade')
    dia_mensalidade = models.IntegerField(verbose_name='Dia da Mensalidade')
    pessoa = models.ForeignKey(Pessoa)


    def __str__(self):
        return str(self.pessoa)


class ReceberMensalidade(models.Model):
    data_recebimento = models.DateField(verbose_name='Data de Recebimento')
    cliente = models.ForeignKey(Cliente, unique_for_month='data_recebimento', verbose_name='CPF',
                                on_delete=models.PROTECT)
    confirmacao = models.BooleanField()

    def __str__(self):
        return str(self.cliente)

class PontoCliente(models.Model):
    data_entrada = models.DateField(default=datetime.date.today, verbose_name=_('Data de Entrada'))
    data_saida = models.DateField(blank=True, null=True, verbose_name=_('Data de Saída'))
    cliente = models.ForeignKey(Cliente, unique_for_date='data_entrada', on_delete=models.PROTECT)

    def __str__(self):
        return str(self.cliente)

apps/funcionario/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
# Create your models here.
from apps.academia.models import Pessoa


class Funcionario(models.Model):
    salario = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Salário')
    pessoa = models.ForeignKey(Pessoa)

    def __str__(self):
        return str(self.pessoa)

class PagamentoSalario(models.Model):
    data_recebimento = models.DateField(verbose_name='Data de Recebimento')
    confirmacao = models.BooleanField()
    funcionario = models.ForeignKey(Funcionario, unique_for_month='data_recebimento', verbose_name='CPF',
                                    on_delete=models.PROTECT)

    def __str__(self):
        return str(self.funcionario)


class PontoCliente(models.Model):
    data_entrada = models.DateField(default=datetime.date.today, verbose_name=_('Data de Entrada'))
    data_saida = models.DateField(blank=True, null=True, verbose_name=_('Data de Saída'))
    funcionario = models.ForeignKey(Funcionario, unique_for_date='data_entrada', on_delete=models.PROTECT)

    def __str__(self):
        return str(self.funcionario)

apps/academia/forms.py
from django import forms


class Logar(forms.Form):
    login = forms.CharField(max_length=20)
    senha = forms.CharField(max_length=20)

apps/academia/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from apps.funcionario.models import *
from apps.academia.models import *
from .forms import *


# Create your views here.
def index(request):
    funcionarios = Funcionario.objects.all()
    estruturas = FotosEstrutura.objects.all()
    precos = Precos.objects.all()
    servicos = Servicos.objects.all()
    context = {
        'funcionario':funcionarios,
        'estruturas':estruturas,
        'precos': precos,
        'servicos': servicos,
    }
    return render(request, 'academia/index.html', context)

@login_required
def base(request):
    return render(request, 'academia/cliente.html', {})


def login(request):
    entrar = Logar(request.POST or None)
    context = {'entrar': entrar,}
    if entrar.is_valid():
        form_dado = entrar.cleaned_data
        loginForm = form_dado['login']
        senhaForm = form_dado['senha']

        if loginForm == 'admin' and senhaForm == 'admin123':
            ok = True
            context['ok'] = ok
            return render(request, 'academia/ponto.html', context)
    return render(request, 'academia/login.html', context)

apps/cliente/views.py
from django.shortcuts import render

# Create your views here.

apps/funcionario/views.py
from django.shortcuts import render

# Create your views here.

templates/academia/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{% block title %}Academy Factory - Uma Academia Diferente | ACFactory {% endblock %}</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/lightbox.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  <link id="{% static 'css-preset' %}" href="{% static 'css/presets/preset1.css' %}" rel="stylesheet">
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
  <link href="{% static 'css/login.css' %}" rel="stylesheet">

  <!--[if lt IE 9]>
  <script src="{% static 'js/html5shiv.js' %}"></script>
  <script src="{% static 'js/respond.min.js' %}"></script>
  <![endif]-->

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
</head><!--/head-->

<body>

<!--.preloader-->
<div class="preloader"> <i class="fa fa-circle-o-notch fa-spin"></i></div>
<!--/.preloader-->
{% block header %}
<header id="home">
  {% block home %}
  <div id="home-slider" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
      <div class="item active" style="background-image: url({% static 'img/slider/1.jpg' %})">
        <div class="caption">
          <h1 class="animated fadeInLeftBig">Bem Vindo a <span>Academy Factory</span></h1>
          <p class="animated fadeInRightBig">Musculação - Danças - Aeróbica - Natação</p>
          <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Conheça mais</a>
        </div>
      </div>
      <div class="item" style="background-image: url({% static 'img/slider/2.jpg' %})">
        <div class="caption">
          <h1 class="animated fadeInLeftBig">Faça parte da <span>Academy Factory</span></h1>
          <p class="animated fadeInRightBig">Musculação - Danças - Aeróbica - Natação</p>
          <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Conheça mais</a>
        </div>
      </div>
      <div class="item" style="background-image: url({% static 'img/slider/3.jpg' %})">
        <div class="caption">
          <h1 class="animated fadeInLeftBig">Somos <span>Academy Factory</span></h1>
          <p class="animated fadeInRightBig">Musculação - Danças - Aeróbica - Natação</p>
          <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Conheça mais</a>
        </div>
      </div>
    </div>
    <a class="left-control" href="#home-slider" data-slide="prev"><i class="fa fa-angle-left"></i></a>
    <a class="right-control" href="#home-slider" data-slide="next"><i class="fa fa-angle-right"></i></a>

    <a id="tohash" href="#services"><i class="fa fa-angle-down"></i></a>
  </div><!--/#home-slider-->
  {% endblock %}
  {% block nav %}
  <div class="main-nav">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'academia:index' %}">
          <h1><img class="img-responsive" src="{% static 'img/logo.png' %}" alt="logo"></h1>
        </a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="scroll active"><a href="#home">Home</a></li>
          <li class="scroll"><a href="#services">Serviços</a></li>
          <li class="scroll"><a href="#about-us">Sobre nós</a></li>
          <li class="scroll"><a href="#portfolio">Fotos</a></li>
          <li class="scroll"><a href="#team">Equipe</a></li>
          <li class="scroll"><a href="#login">Login</a></li>
          <li class="scroll"><a href="#contact">Contato</a></li>
        </ul>
      </div>
    </div>
  </div><!--/#main-nav-->
  {% endblock %}
</header><!--/#home-->
{% endblock %}

{% block section %}
{% endblock %}

{% block footer %}
<footer id="footer">
  <div class="footer-top wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
    <div class="container text-center">
      <div class="footer-logo">
        <a href="{% url 'academia:index' %}"><img class="img-responsive" src="{% static 'img/logo.png' %}" alt=""></a>
      </div>
      <div class="social-icons">
        <ul>
          <li><a class="envelope" href="#"><i class="fa fa-envelope"></i></a></li>
          <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a class="tumblr" href="#"><i class="fa fa-tumblr-square"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <p>&copy; 2017 Academy Factory.</p>
        </div>
        <div class="col-sm-6">
          <p class="pull-right">Criado por <a href="#">Jaqueline e Vanniery</a></p>
        </div>
      </div>
    </div>
  </div>
</footer>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="{% static 'js/jquery.inview.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/mousescroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/smoothscroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lightbox.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
{% endblock %}


</body>
</html>

templates/academia/cliente.html
{% extends 'academia/base.html' %}
{% load staticfiles %}
<script>$('.main-nav').addClass('navbar-fixed-top');</script>
{% block header %}
{% include 'academia/nav.html' %}
{% endblock %}


{% block section %}
<header>
<section>
    <p>oiiii</p>
</section>
<section>
    <p>oiiii</p>
</section>
<section>
    <p>oiiii</p>
</section>
    </header>
{% endblock %}

templates/academia/nav.html
{% block nav %}
{% load staticfiles %}
<div class="main-nav">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'academia:index' %}">
        <h1><img class="img-responsive" src="{% static 'img/logo.png' %}" alt="logo"></h1>
      </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="scroll active"><a href="#services">Service</a></li>
        <li class="scroll"><a href="#about-us">About Us</a></li>
        <li class="scroll"><a href="#portfolio">Portfolio</a></li>
        <li class="scroll"><a href="#team">Team</a></li>
        <li class="scroll"><a href="#login">Login</a></li>
        <li class="scroll"><a href="#contact">Contact</a></li>
      </ul>
    </div>
  </div>
</div><!--/#main-nav-->
{% endblock %}